server.port: 8000
eureka.client.serviceUrl.defaultZone: https://ashwin-discovery-service.herokuapp.com/eureka
spring:
  application.name: customer-service
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true